### PR TITLE
Replace references to the Toulouse edition with Lyon

### LINKED ISSUE #1: Update Sepia to Agen 1 edition
### Description
Update Sepia to Agen 1 edition instead of Toulouse edition.

### Motivation
Since Agen 1 is released of the protocol, an update of sepia repository would be good to keep it up to date with the rest of eiffel.

### Exemplification
In https://eiffel-community.github.io/eiffel-sepia/ there are references to the Toulouse edition.

### Benefits
We keep the sepia repository relevant

### Possible Drawbacks
No drawbacks that I can see.

### PR DESCRIPTION
**Pull request by magnusbaeck**
### Applicable Issues
Fixes #1 

### Description of the Change
It was quite a while since Toulouse was replaced by Agen, Agen-1,    and Paris and several months since the Lyon edition was released    to it's about time we update the references in Sepia.
    
Since Toulouse the ID event has been added and it was included in the "Test Outcome Analysis" pipeline actor role in overview.svg. That might not be a perfect match but it's probably the best we've got at this point.

### Alternate Designs
None.

### Benefits
We're no longer linking to an obsolete protocol edition.

### Possible Drawbacks
None.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I    have the right to submit it under the open source license    indicated in the file; or

(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or

(c) The contribution was provided directly to me by some other    person who certified (a), (b) or (c) and I have not modified    it.

(d) I understand and agree that this project and the contribution    are public and that a record of the contribution (including all    personal information I submit with it, including my sign-off) is    maintained indefinitely and may be redistributed consistent with    this project or the open source license(s) involved.

Signed-off-by: Magnus Bäck \<magnus.back@axis.com>

### CODE REVIEW

**Review by t-persson — APPROVED** [review]

**Review by e-backmark-ericsson — CHANGES_REQUESTED** [review]
Since Toulouse we have got a new event type - EiffelIssueDefinedEvent. It should be added to the architecture somewhere.

**Comment by magnusbaeck** [comment]
> Since Toulouse we have got a new event type - EiffelIssueDefinedEvent. It should be added to the architecture somewhere.

Indeed, good catch:

    $ git diff-tree --name-only --diff-filter=A -r edition-toulouse..edition-paris -- eiffel-vocabulary
    eiffel-vocabulary/EiffelIssueDefinedEvent.md

I don't quite see how ID would fit into an existing actor. IV is in its own "Test Outcome Analysis" box but ID doesn't fit in there. How about a new "Issue Management" actor that includes ID?

**Comment by e-backmark-ericsson** [comment]
> I don't quite see how ID would fit into an existing actor. IV is in its own "Test Outcome Analysis" box but ID doesn't fit in there. How about a new "Issue Management" actor that includes ID?

Maybe. Should we then move IV into that box as well? I have a feeling that the boxes are too finegrained today to be able to add more events to them. We risk having one box for each new event coming. Maybe we need to revisit/define the meaning of the boxes - why are they there, how are they supposed to be divided, etc.

**Comment by magnusbaeck** [comment]
> Should we then move IV into that box as well?

That wasn't my intention, but I guess it depends on the definition of an Issue Management role. If that role is concerned with issue tracker integration I suppose both ID and IV would fit reasonably well, although determination of whether IV should be sent is a form of test outcome analysis.

> I have a feeling that the boxes are too finegrained today to be able to add more events to them. We risk having one box for each new event coming.

Yes, I also feel that they're quite narrow and specialized and it's not clear how they're supposed to be used. I wonder if it would be useful to focus on actors that actually consume events. SCC, SCS, and ID (and possibly other *DefinedEvent) are often used to model reality and produced by actors that translate reality to Eiffel events. I'm almost inclined to group them into a larger "reality translator" bucket.

> Maybe we need to revisit/define the meaning of the boxes - why are they there, how are they supposed to be divided, etc.

Yes. But I think it would be unfortunate to hold back this PR. Should we attempt to find an acceptable supposedly short-term way of getting the ID event into overview.svg so we can get rid of the Toulouse references and then attack the larger discussion?

**Comment by m-linner-ericsson** [comment]
Agree with you @magnusbaeck maybe put it somewhere just to get this out of the door.

**Comment by magnusbaeck** [comment]
There, PR rebased and updated with references to Lyon instead of Paris. Since the branch needed to be updated from the upstream I did a non-fast forward update even though that goes against the recommendations.

Added ID to the Test Outcome Analysis role. See https://raw.githubusercontent.com/magnusbaeck/eiffel-sepia/9b8c110f9dfedff54e62e54ed7e3a5fdca110f5c/svg/overview.svg.

**Review by e-backmark-ericsson — APPROVED** [review]

**Review by m-linner-ericsson — APPROVED** [review]
@magnusbaeck I changed the title of the PR to Lyon

**Comment by magnusbaeck** [comment]
> I changed the title of the PR to Lyon

Thanks! I remembered to change the PR description but forgot about the title.

**Pull request merged**
