### PR TITLE
Add a landscape picture

### PR DESCRIPTION
**Pull request by m-linner-ericsson**
### Applicable Issues
In order to have a better overview of the different components in the Eiffel community this PR aims to provide a landscape picture

### Description of the Change
A landscape picture of the different components in the Eiffel community.

To edit the picture open it via draw.io (where you can interact directly with GitHub)

### Alternate Designs
We could use the landscape functionality use by Linux foundation e.g. https://landscape.cd.foundation/ or https://landscape.cncf.io/ but the effort of getting one of those up and running was considered too much.

### Benefits
One can see an overview of what components we have in the Eiffel Community

### Possible Drawbacks
Might be hard to find as it is not linked yet. Please suggest a good place for it!

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Mattias Linnér mattias.linner@ericsson.om

### CODE REVIEW

**Comment by magnusbaeck** [comment]
Instead of relying on draw.io, how about using SVG? I believe we use that for all other illustrations in the eiffel and eiffel-sepia repositories, plus you can include hyperlinks and view the thing directly in the browser.

**Comment by m-linner-ericsson** [comment]
I added an svg version also. 

I wanted to point out that the logos are PNG need Gimp to update those and the overview picture in sepia was created by using Inkscape.

I think we still need an editor to update the pictures as it would be very cumbersome to update them by editing the text. Thus draw.io does not require you to install a program locally as with Gimp and Inkscape.

**Comment by magnusbaeck** [comment]
Sure, editing SVG by hand isn't a viable option, but I think using draw.io and keeping SVG and/or PNG copies in sync seems like way more work than just having an SVG that you edit locally with (for example) Inkscape. We're also adding a dependency to a third-party site (with a supposedly proprietary data format) that requests read and write access to all your repos and the organizations you're in, something that contributors very well could be uncomfortable about. I had to do some googling to even figure out how I'd go about editing the file.

**Comment by m-linner-ericsson** [comment]
I think including the original file is crucial. @e-backmark-ericsson has had problems editing the SVGs that we have today so therefore we need the original. draw.io offers a local version as well. Maybe we can sync on this during the TC.

**Comment by magnusbaeck** [comment]
Today's SVGs are certainly painful because of #16 but should otherwise be fine. The standalone [overview.svg](https://github.com/eiffel-community/eiffel-sepia/blob/gh-pages/svg/overview.svg) was originally created with Inkscape and opens just fine with that program on my machine.

**Comment by t-persson** [comment]
We should add an "SDKs" box to the landscape image

**Comment by m-linner-ericsson** [comment]
@t-persson Do you have any suggestions on which components should be in that box or should we rename one of them to SDK instead?

**Comment by t-persson** [comment]
> @t-persson Do you have any suggestions on which components should be in that box or should we rename one of them to SDK instead?

I vote for creating a new box and adding eiffelevents-sdk-go (correct name?) & Eiffel Pythonlib in that box. This would mean that Eiffel Pythonlib exists in two boxes, for now, but I think that's okay because it is both of these things.

**Comment by m-linner-ericsson** [comment]
@t-persson Did I get the location of GoER correct?
@magnusbaeck I didn't find the eiffelevents-sdk-go repo so I waited with adding it to the landscape picture.

**Comment by magnusbaeck** [comment]
> Did I get the location of GoER correct?

Not sure what you mean by location, but the service is apparently stylized Goer rather than GoER (https://github.com/eiffel-community/eiffel-goer).

> I didn't find the eiffelevents-sdk-go repo so I waited with adding it to the landscape picture.

Right. I was going to create the repo when I started working on the code (i.e. soon).

**Review by magnusbaeck — COMMENTED** [review]
Two structural issues:

* Does this really belong in the Sepia repo? Wouldn't [github.com/eiffel-community/eiffel-community.github.io](https://github.com/eiffel-community/eiffel-community.github.io) be a better fit?
* Regardless of the repository location, I suppose we should include it in an HTML page?

Three minor things that caught my eye but aren't critical:

* I suggest the newly added "Ml Jmespath Generator" box is renamed "ML Jmespath Generator". "l" and "I" are indistinguishable at this size and with such limited surrounding context.
* The "Store events" box should perhaps be "Store and query events"?
* The "Eiffel Playground" box at the bottom has been misspelt  "Eiffel P Playground".

**Comment by m-linner-ericsson** [comment]
Moved this to the HTML page instead. Please see https://github.com/eiffel-community/eiffel-community.github.io/pull/29

**Pull request closed without merging**
