### PR TITLE
Update Lyon references to Arica

### LINKED ISSUE #21: Update edition references from Lyon to Arica
### Description
All references to the Lyon edition should be updated to Arica.

### Motivation
The Sepia documentation is supposed to reference the most recent edition.

### Exemplification
N/A

### Benefits
Documentation pointing to the most up to date version of the protocol.

### Possible Drawbacks
None.

### PR DESCRIPTION
**Pull request by magnusbaeck**
### Applicable Issues
Fixes #21 

### Description of the Change
The Arica edition has been released so all Sepia references to the previous edition (Lyon) should be replaced with Arica. Arica doesn't contain any new events or anything that would affect the rest of the documentation so it's just a matter of adjusting the URLs.

### Alternate Designs
None.

### Benefits
Documentation links to the current protocol edition.

### Possible Drawbacks
None.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I    have the right to submit it under the open source license    indicated in the file; or

(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or

(c) The contribution was provided directly to me by some other    person who certified (a), (b) or (c) and I have not modified    it.

(d) I understand and agree that this project and the contribution    are public and that a record of the contribution (including all    personal information I submit with it, including my sign-off) is    maintained indefinitely and may be redistributed consistent with    this project or the open source license(s) involved.

Signed-off-by: Magnus Bäck \<magnus.back@axis.com>

### CODE REVIEW

**Review by e-backmark-ericsson — APPROVED** [review]
It's hard to know if any Lyon references where missed, but I rely on that this PR is based on a 'grep -i lyon' so I can't see how it could go wrong :)

**Comment by magnusbaeck** [comment]
Yep, `sed -i 's/edition-lyon/edition-arica/g' $(git grep -l edition-lyon)` followed by a manual fix of the remaining Lyon reference in the link text in index.html.

**Review by m-linner-ericsson — APPROVED** [review]
LGTM but should we have another way of handling this. Is it a good process to have to update these links every time we release a new edition?

**Review by t-persson — APPROVED** [review]

**Comment by magnusbaeck** [comment]
> Is it a good process to have to update these links every time we release a new edition?

I sense a rhetorical question :-) But no, this clearly isn't ideal. I suppose we'd have to generate the pages (or have a completely dynamic site) to really improve the situation.

**Comment by m-linner-ericsson** [comment]
I guess the only other option would be to link to master (which have other consequences). We could at least describe somewhere why we want to link to specific version (eg being able to update sepia for a bigger change in the protocol, being able to update sepia in parallel with the protocol etc.)

**Pull request merged**
